name: holder-server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # Add this step to delete the existing 'dist' folder on the remote server
      - name: Delete existing dist folder
        uses: appleboy/ssh-action@master
        with:
          host: 3.82.189.81
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: rm -rf /home/ec2-user/server/dist

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 3.82.189.81
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'dist/' # Update this line to point to your 'dist' folder
          target: /home/ec2-user/server

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 3.82.189.81
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ec2-user/server/dist
            rm .env
            echo "TYPE=${{ secrets.FIREBASE_TYPE }}" >> /home/ec2-user/server/dist/.env
            echo "PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> /home/ec2-user/server/dist/.env
            echo "PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}" >> /home/ec2-user/server/dist/.env
            echo "PRIVATE_KEY=$(echo '${{ secrets.FIREBASE_PRIVATE_KEY }}' | base64 -d)" >> /home/ec2-user/server/dist/.env
            echo "CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> /home/ec2-user/server/dist/.env
            echo "CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }}" >> /home/ec2-user/server/dist/.env
            echo "AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }}" >> /home/ec2-user/server/dist/.env
            echo "TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }}" >> /home/ec2-user/server/dist/.env
            echo "AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}" >> /home/ec2-user/server/dist/.env
            echo "CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}" >> /home/ec2-user/server/dist/.env
            yarn install
            pm2 delete holder-api
            pm2 start yarn --name holder-api -- start
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
